language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler -v 1.10.6
bundler_args: --deployment
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec
env:
  global:
    - secure: "PhPmXlHn+zvfRVEYcdYYchOA7FDP8aXORN5gMjhjAmiNCknetwhtw30aVM9m81JxnusD5HFJYsJRQFfwAbFIjBMt/QfqjX+FnBII4Yd5swbXhABK9QRdrxzN4sPvhItPYWB6azxh/VUuRo4OlxLcjWPxF9QWQTyAuLapsagN0sDWdO7bZyUAcf86DcTo9UYJn2ZCDe4uiysYld/pleMt7PTUiaVCo2Rp5mkEcdStUTzHl9LPPtEvgCjI/ecpI1fX86eCcobDNQoAOYQEKeGbhwROHlNbrOS2OnD56duApNSM6EySG9QbPgOlXgf/f2Y7MlDEd4zYKZ3kJ/mxUJWnKfwdYGx/7a50vc79ocw0i8nh0QYssZdfX/8vnLSopLGEvhaDFnShDa33x+2jo6MdIjFvXSMnxs6/XxwbcFpstZ0XiUSOJc4xCUyaxoZVl8JAdO4MEI7Ii9i5b54RL/c0X7a9oJX9GRp2U336p0de2Lmu+NXcfwjk4AJwtddtq2uFQwPQafmJ2BUTZGIxFvwpc3WwZh0KhJsUgm1YRqQCWVt8qargVSEcNMKi/jD70m2Tl6oe0EQQum7wUk8s99rt7JUXjsbIZEvOg2g04mtHZgZvjJtncr/GLtM8LE7fNjRODJVTqCIpOVrO9erP44ZzNBTpFS5zQRBddG7zlhvQ2tU="