# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65229c9bec71c882946871afb5dc599690b6c5e00aa7cdb65014ece55f5b09375b765bb4738a4525342de8661e1c65f92825aba11e44424a47541ca42ea8f24e

test:
  secret_key_base: 233ddc31cc9e5c33d1ed91d4b3225112dddaf0a83728bb19024c1c59a967dd6149cb349520614e5d3712c72a5cbbd13eac90f59fbe257a1578f9b7f283b92973
  oauth_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] || 'oauth_consumer_key' %>
  oauth_token: <%= ENV['TWITTER_ACCESS_TOKEN'] || 'oauth_token' %>
  Bearer:  <%= ENV['DOORKEEPER_TOKEN'] || 'Bearer' %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
